version: '3'
services:
    fxland:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: fxland
        restart: always
        volumes:
          - ./dist:/usr/src/app/
          - ./ecosystem.config.js/:/usr/src/app/ecosystem.config.js
        networks:
            - proxy
        ports:
            - "80:3000"
  
networks:
    proxy:
        external: true